name = "LoadingMatrices"
uuid = "e727e771-cdf2-4e4f-9de3-9178de403442"
authors = ["Sam Urmy <oceanographerschoice@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
